INSERT INTO [dbo].[Student] ([LastName], [FirstName], [Username], [Password]) VALUES ('Tables', 'Bobby', 'btables', 'Tr0ub4dor&3')
INSERT INTO [dbo].[Student] ([LastName], [FirstName], [Username], [Password]) VALUES ('Tables', 'Bobby'' OR ''a''=''a', 'btables2', 'correcthorsebatterystaple')
INSERT INTO [dbo].[Student] ([LastName], [FirstName], [Username], [Password]) VALUES ('Skywalker', 'Anakin', 'sithlord', 'ihatesand1234')
INSERT INTO [dbo].[Student] ([LastName], [FirstName], [Username], [Password]) VALUES ('Morrison', 'Jack', 'soldier76', 'Number1Dad')
INSERT INTO [dbo].[Student] ([LastName], [FirstName], [Username], [Password]) VALUES ('Midoriya', 'Izuku', 'deku', 'OneForAll')